/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.src.test.java.java_100;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
